export const promoBooks = [
    {
       url: 'https://bestlifeonline.com/wp-content/uploads/sites/3/2020/10/Harry-Potter-and-the-Chamber-of-Secrets-book-cover.jpg',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '345 с',
       pastPrice: '745 с',
       discount: '(-150%)',
    },
    {
       url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r2IDk4r1k9kCAbmWZ82TYbXyqKr65ZnLkA&usqp=CAU',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '355 с',
       pastPrice: '445 с',
       discount: '(-70%)',
    },
    {
       url: 'https://cdn.lifehack.org/wp-content/uploads/2015/03/9780618640157_custom-s6-c30.jpg',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '365 с',
       pastPrice: '345 с',
       discount: '(-20%)',
    },
    {
       url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnjFzoRSWilOLNcqwyCtzaGWMQ-FtEXFD8IXVAI8gtQhSOHgfxlSkqFP5IHikU-dHnxI&usqp=CAU',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '375 с',
       pastPrice: '395 с',
       discount: '(-50%)',
    },
    {
       url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1DrHeVQqgcMVZj_mKGKFvW3AGtdKZ0D1jvw&usqp=CAU',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '375 с',
       pastPrice: '395 с',
       discount: '(-50%)',
    },
    {
       url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdAPfqcUpClxlHjCnszGTmuODGW4csALsIQ&usqp=CAU',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '375 с',
       pastPrice: '395 с',
       discount: '(-50%)',
    },
    {
       url: 'https://i.insider.com/5846d102ba6eb66d268b7739?width=600&format=jpeg&auto=webp',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '375 с',
       pastPrice: '395 с',
       discount: '(-50%)',
    },
    {
       url: 'https://static.bookofthemonth.com/covers/list/ItEndsWithUs_200x300.jpg',
       bookName: 'Тонкое искусство пофигизма',
       bookAuthor: 'Марк Мэнсон',
       bookPrice: '375 с',
       pastPrice: '395 с',
       discount: '(-50%)',
    },
    {
        url: 'https://bestlifeonline.com/wp-content/uploads/sites/3/2020/10/Harry-Potter-and-the-Chamber-of-Secrets-book-cover.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '345 с',
        pastPrice: '745 с',
        discount: '(-150%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r2IDk4r1k9kCAbmWZ82TYbXyqKr65ZnLkA&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '355 с',
        pastPrice: '445 с',
        discount: '(-70%)',
     },
     {
        url: 'https://cdn.lifehack.org/wp-content/uploads/2015/03/9780618640157_custom-s6-c30.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '365 с',
        pastPrice: '345 с',
        discount: '(-20%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnjFzoRSWilOLNcqwyCtzaGWMQ-FtEXFD8IXVAI8gtQhSOHgfxlSkqFP5IHikU-dHnxI&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1DrHeVQqgcMVZj_mKGKFvW3AGtdKZ0D1jvw&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdAPfqcUpClxlHjCnszGTmuODGW4csALsIQ&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://i.insider.com/5846d102ba6eb66d268b7739?width=600&format=jpeg&auto=webp',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://static.bookofthemonth.com/covers/list/ItEndsWithUs_200x300.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://bestlifeonline.com/wp-content/uploads/sites/3/2020/10/Harry-Potter-and-the-Chamber-of-Secrets-book-cover.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '345 с',
        pastPrice: '745 с',
        discount: '(-150%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r2IDk4r1k9kCAbmWZ82TYbXyqKr65ZnLkA&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '355 с',
        pastPrice: '445 с',
        discount: '(-70%)',
     },
     {
        url: 'https://cdn.lifehack.org/wp-content/uploads/2015/03/9780618640157_custom-s6-c30.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '365 с',
        pastPrice: '345 с',
        discount: '(-20%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnjFzoRSWilOLNcqwyCtzaGWMQ-FtEXFD8IXVAI8gtQhSOHgfxlSkqFP5IHikU-dHnxI&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1DrHeVQqgcMVZj_mKGKFvW3AGtdKZ0D1jvw&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdAPfqcUpClxlHjCnszGTmuODGW4csALsIQ&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://i.insider.com/5846d102ba6eb66d268b7739?width=600&format=jpeg&auto=webp',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://static.bookofthemonth.com/covers/list/ItEndsWithUs_200x300.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://bestlifeonline.com/wp-content/uploads/sites/3/2020/10/Harry-Potter-and-the-Chamber-of-Secrets-book-cover.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '345 с',
        pastPrice: '745 с',
        discount: '(-150%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r2IDk4r1k9kCAbmWZ82TYbXyqKr65ZnLkA&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '355 с',
        pastPrice: '445 с',
        discount: '(-70%)',
     },
     {
        url: 'https://cdn.lifehack.org/wp-content/uploads/2015/03/9780618640157_custom-s6-c30.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '365 с',
        pastPrice: '345 с',
        discount: '(-20%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnjFzoRSWilOLNcqwyCtzaGWMQ-FtEXFD8IXVAI8gtQhSOHgfxlSkqFP5IHikU-dHnxI&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1DrHeVQqgcMVZj_mKGKFvW3AGtdKZ0D1jvw&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdAPfqcUpClxlHjCnszGTmuODGW4csALsIQ&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://i.insider.com/5846d102ba6eb66d268b7739?width=600&format=jpeg&auto=webp',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://static.bookofthemonth.com/covers/list/ItEndsWithUs_200x300.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://bestlifeonline.com/wp-content/uploads/sites/3/2020/10/Harry-Potter-and-the-Chamber-of-Secrets-book-cover.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '345 с',
        pastPrice: '745 с',
        discount: '(-150%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r2IDk4r1k9kCAbmWZ82TYbXyqKr65ZnLkA&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '355 с',
        pastPrice: '445 с',
        discount: '(-70%)',
     },
     {
        url: 'https://cdn.lifehack.org/wp-content/uploads/2015/03/9780618640157_custom-s6-c30.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '365 с',
        pastPrice: '345 с',
        discount: '(-20%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnjFzoRSWilOLNcqwyCtzaGWMQ-FtEXFD8IXVAI8gtQhSOHgfxlSkqFP5IHikU-dHnxI&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1DrHeVQqgcMVZj_mKGKFvW3AGtdKZ0D1jvw&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdAPfqcUpClxlHjCnszGTmuODGW4csALsIQ&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://i.insider.com/5846d102ba6eb66d268b7739?width=600&format=jpeg&auto=webp',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://static.bookofthemonth.com/covers/list/ItEndsWithUs_200x300.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://bestlifeonline.com/wp-content/uploads/sites/3/2020/10/Harry-Potter-and-the-Chamber-of-Secrets-book-cover.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '345 с',
        pastPrice: '745 с',
        discount: '(-150%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r2IDk4r1k9kCAbmWZ82TYbXyqKr65ZnLkA&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '355 с',
        pastPrice: '445 с',
        discount: '(-70%)',
     },
     {
        url: 'https://cdn.lifehack.org/wp-content/uploads/2015/03/9780618640157_custom-s6-c30.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '365 с',
        pastPrice: '345 с',
        discount: '(-20%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnjFzoRSWilOLNcqwyCtzaGWMQ-FtEXFD8IXVAI8gtQhSOHgfxlSkqFP5IHikU-dHnxI&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1DrHeVQqgcMVZj_mKGKFvW3AGtdKZ0D1jvw&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdAPfqcUpClxlHjCnszGTmuODGW4csALsIQ&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://i.insider.com/5846d102ba6eb66d268b7739?width=600&format=jpeg&auto=webp',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://static.bookofthemonth.com/covers/list/ItEndsWithUs_200x300.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://bestlifeonline.com/wp-content/uploads/sites/3/2020/10/Harry-Potter-and-the-Chamber-of-Secrets-book-cover.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '345 с',
        pastPrice: '745 с',
        discount: '(-150%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r2IDk4r1k9kCAbmWZ82TYbXyqKr65ZnLkA&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '355 с',
        pastPrice: '445 с',
        discount: '(-70%)',
     },
     {
        url: 'https://cdn.lifehack.org/wp-content/uploads/2015/03/9780618640157_custom-s6-c30.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '365 с',
        pastPrice: '345 с',
        discount: '(-20%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqnjFzoRSWilOLNcqwyCtzaGWMQ-FtEXFD8IXVAI8gtQhSOHgfxlSkqFP5IHikU-dHnxI&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1DrHeVQqgcMVZj_mKGKFvW3AGtdKZ0D1jvw&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdAPfqcUpClxlHjCnszGTmuODGW4csALsIQ&usqp=CAU',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://i.insider.com/5846d102ba6eb66d268b7739?width=600&format=jpeg&auto=webp',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
     {
        url: 'https://static.bookofthemonth.com/covers/list/ItEndsWithUs_200x300.jpg',
        bookName: 'Тонкое искусство пофигизма',
        bookAuthor: 'Марк Мэнсон',
        bookPrice: '375 с',
        pastPrice: '395 с',
        discount: '(-50%)',
     },
 ]